### PR TITLE
fix: only ensure leading and ending slash for internal links

### LINKED ISSUE #2: [Bug] failed to redirect to external link
## Summary

If we write `redirects` files as follows:

```
/a/ https://a.com/
```

it will be determined as internal redirect.

## Actual

The redirects will be serialized as:

```
 [
  [
    '/a/',
    '/https://a.com'
  ]
]
```

## Expected

```
 [
  [
    '/a/',
    'https://a.com'
  ]
]
```

### PR DESCRIPTION
**Pull request by ulivz**
Close #2

### CODE REVIEW

File: lib/index.js [hunk 1]
```diff
@@ -40,7 +51,7 @@ module.exports = (options = {}, ctx) => {
     const filename = pagePath.replace(/\/$/, '/index.html').replace(/^\//, '')
     const filePath = path.resolve(ctx.outDir, filename)
     await fs.ensureDir(path.dirname(filePath))
-    const html = getRedirectHtml({ url, redirectUrl, countdown, routerBase: ctx.base })
+    const html = getDirectHtml({ url, redirectUrl, countdown, routerBase: ctx.base })
```
Comment (TsangKalung) [inline lib/index.js]: Don't rename this function.

**Review by TsangKalung — APPROVED** [review]
LGTM.
